### ISSUE TITLE
--which_set test

### ISSUE THREAD

**Issue by csgeqian** [songguocode/TADAM#10]
Thank you very much for your excellent work!I tried to add "-- which_set test"to get the test results, but failed

python -m lib.tracking.tracker_test --result-name TADAM_MOT17_test --config TADAM_MOT17 --which_set test
2021-11-16 09:54:25 [INFO]:     Merged config from 'lib/configs/TADAM_MOT17.yaml'
2021-11-16 09:54:25 [INFO]:     Sequence: MOT17-01-DPM
2021-11-16 09:54:26 [INFO]:     Successfully loaded pretrained weights from '/home/geqian/Download/TADAM/lib/configs/output/models/TADAM_MOT17.pth'
2021-11-16 09:54:26 [WARNING]:  ** The following layers are discarded due to unmatched keys or layer size: '['roi_heads.id_module.classifier.weight', 'roi_heads.id_module.classifier.bias', 'memory_net.loss_classifier.weight', 'memory_net.loss_classifier.bias']'
2021-11-16 09:54:28 [INFO]:     Started processing frames
Traceback (most recent call last):
  File "/home/geqian/miniconda3/envs/TADAM/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/geqian/miniconda3/envs/TADAM/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/geqian/Download/TADAM/lib/tracking/tracker_test.py", line 158, in <module>
    mytest(config, logger, dataset=config.NAMES.DATASET, which_set=args.which_set,
  File "/home/geqian/Download/TADAM/lib/tracking/tracker_test.py", line 119, in mytest
    mytest_sequence(dataloader, config, logger, seq_result_file, plot_frames)
  File "/home/geqian/Download/TADAM/lib/tracking/tracker_test.py", line 40, in mytest_sequence
    for frame_id, batch in enumerate(dataloader):
  File "/home/geqian/miniconda3/envs/TADAM/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/geqian/miniconda3/envs/TADAM/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/geqian/miniconda3/envs/TADAM/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/geqian/miniconda3/envs/TADAM/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/geqian/miniconda3/envs/TADAM/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/geqian/miniconda3/envs/TADAM/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/geqian/miniconda3/envs/TADAM/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/geqian/Download/TADAM/lib/dataset/mot.py", line 273, in __getitem__
    det_boxes, det_scores, gt_boxes, gt_ids, gt_visibilities = self._get_annotation(idx)
ValueError: not enough values to unpack (expected 5, got 4)

**Comment by hanzi326** [comment]
Hi! Thanks for your effort!
My situation is the same as yours, please ask if you find a solution

**Comment by songguocode** [comment]
It is fixed now. Please try again. Thanks!

**Comment by csgeqian** [comment]
Thank you very much for your excellent work! Can test set evaluation be implemented in code? Or do you have to submit it to the official website for evaluation?

**Comment by LiangXiaoguo** [comment]
> Thank you very much for your excellent work! Can test set evaluation be implemented in code? Or do you have to submit it to the official website for evaluation?

You can register your MOTChallenge website account to submit your test results

**Comment by csgeqian** [comment]
I can't register motchallenge website account

**Comment by csgeqian** [comment]
> > 非常感谢您的出色工作！测试集评估可以在代码中实现吗？还是必须要提交到官网进行评估？
> 
> 您可以注册您的 MOTChallenge 网站帐户以提交您的测试结果
I can't register motchallenge website account

**Comment by csgeqian** [comment]
> > Thank you very much for your excellent work! Can test set evaluation be implemented in code? Or do you have to submit it to the official website for evaluation?
> 
> You can register your MOTChallenge website account to submit your test results

I can't register motchallenge website account

**Comment by csgeqian** [comment]
> > Thank you very much for your excellent work! Can test set evaluation be implemented in code? Or do you have to submit it to the official website for evaluation?
> 
> You can register your MOTChallenge website account to submit your test results
Thanks！I can't register motchallenge website account. Can you help me? Can you add a contact information

**Comment by Autoyou** [comment]
> > > Thank you very much for your excellent work! Can test set evaluation be implemented in code? Or do you have to submit it to the official website for evaluation?
> > 
> > 
> > You can register your MOTChallenge website account to submit your test results
> > Thanks！I can't register motchallenge website account. Can you help me? Can you add a contact information
Have you adress the MOTChallenge website account problem? I face the same problem.

**Comment by Autoyou** [comment]
> > > Thank you very much for your excellent work! Can test set evaluation be implemented in code? Or do you have to submit it to the official website for evaluation?
> > 
> > 
> > You can register your MOTChallenge website account to submit your test results
> > Thanks！I can't register motchallenge website account. Can you help me? Can you add a contact information
Have you adress the MOTChallenge website account problem? I face the same problem.
