### ISSUE TITLE
Trajectory

### ISSUE THREAD

**Issue by LiangXiaoguo** [songguocode/TADAM#13]
I tried to visualize on the test set and the following error occurred. Importantly, the visualization on the train set is normal.
2022-01-27 12:57:01 [INFO]:     Merged config from 'lib/configs/TADAM_MOT16.yaml'
2022-01-27 12:57:01 [INFO]:     Showing MOT16/test/MOT16-06
2022-01-27 12:57:01 [INFO]:     Loaded result file at 'output/results/MOT16/test16result/MOT16-06.txt'
Traceback (most recent call last):
  File "/home/lab509/miniconda3/envs/lxg/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lab509/miniconda3/envs/lxg/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/disk1-1t/liangxiaoguo/TADAM/lib/utils/visualization.py", line 360, in <module>
    show_mot(dataloader, config.PATHS.DATASET_ROOT, config.NAMES.DATASET, args.which_set, sequence,
  File "/media/disk1-1t/liangxiaoguo/TADAM/lib/utils/visualization.py", line 181, in show_mot
    det_scores = det_scores[0].detach().clone().cpu().numpy()
AttributeError: 'NoneType' object has no attribute 'detach'

**Comment by Leo63963** [comment]
I got the same question.

**Comment by HeBotong** [comment]
> I tried to visualize on the test set and the following error occurred. Importantly, the visualization on the train set is normal. 2022-01-27 12:57:01 [INFO]: Merged config from 'lib/configs/TADAM_MOT16.yaml' 2022-01-27 12:57:01 [INFO]: Showing MOT16/test/MOT16-06 2022-01-27 12:57:01 [INFO]: Loaded result file at 'output/results/MOT16/test16result/MOT16-06.txt' Traceback (most recent call last): File "/home/lab509/miniconda3/envs/lxg/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/lab509/miniconda3/envs/lxg/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/media/disk1-1t/liangxiaoguo/TADAM/lib/utils/visualization.py", line 360, in show_mot(dataloader, config.PATHS.DATASET_ROOT, config.NAMES.DATASET, args.which_set, sequence, File "/media/disk1-1t/liangxiaoguo/TADAM/lib/utils/visualization.py", line 181, in show_mot det_scores = det_scores[0].detach().clone().cpu().numpy() AttributeError: 'NoneType' object has no attribute 'detach'

Did you solve it? I had the same problem
